name: Default
priority: 1
count: 0
maps:
- Warlock
- Divided
- Agrostid
- Limbo II
- "Ruediger's Oasis"
- Kaldr
- Desolated Frontier
- Snowy Wars
- Justice
- Gralien
- Grassy Mound
- Wrath Tor RAGE
- Placid Spring
- Desolate Gully
- SuperCube
- BalloonsDTM
- Flow
- OutCast
