name: Default
priority: 1
count: 0
maps:
- Sheol
- Vertex
- Toss Up
- Maple Falls
- Nyah
- Gelid 2
- Covert Fortress
- "Pompeii: Mini"
- Garden
- Come Summertime
- Wilky Way
- Snowy Frontier
- Lagoon
- Dead Waters
- Rig FFA
- Downforce
- Finis
- Hekla
- Geometric
- "Interitus: Mini"
