name: Default
priority: 1
count: 0
maps:
- Sheol
- Vertex
- Geometric
- Hekla
- The Bug
- Gelid 2
- Come Summertime
- Alien
- Garden
- Covert Fortress
- Wilky Way
- Snowy Frontier
- Lagoon
- Dead Waters
- Under The Sea
- Downforce
- Finis
- Maple Falls
- Toss Up
- Nyah
