name: Default
priority: 1
count: 0
maps:
- Atom
- Come Summertime
- Snowy Frontier
- Garden
- Under The Sea
- Dry Outpost
- Hekla
- Nyah
- Finis
- Mesa
- Downforce
- Wilky Way
- Dead Waters
- Geometric
- Lagoon
- Gelid 2
- The Bug
- Toss Up
- Vertex
- Maple Falls
