name: Default
priority: 1
count: 0
maps:
- Cursed Library
- Dry Outpost
- GRAVErnment
- Alley
- Dead Waters
- Area 51
- Covert Fortress
- Snowy Frontier
- Bloody Maple
- Vertex
- Arctic Ruins
- Decay
- Finis
- Desolate Gully CTW
- "InSCAREitus: Mini"
- Toss Up
- Come Halloweentime
- Hekla
- Bonehenge
- Garden
