name: Default
priority: 1
count: 0
maps:
- Garden
- Decay
- Hekla
- Dry Outpost
- Finis
- Snowy Frontier
- Covert Fortress
- Wilky Way
- Stonehenge
- "Interitus: Mini"
- Vertex
- Government
- Gelid 2
- Nyah
- Sheol
- Lagoon
- Toss Up
- Downforce
