name: Default
priority: 1
count: 0
maps:
- Cursed Library
- Lagoon
- Rig FFA
- Tiny Timburs
- Dead Waters
- North Winds
- Covert Fortress
- Snowy Frontier
- Bulwark
- Come Summertime
- Arctic Ruins
- Decay
- Finis
- Desolate Gully CTW
- "Interitus: Mini"
- Pompeii Mini
- Downforce
- Hekla
- Alien
- Garden
