name: Default
priority: 1
count: 0
maps:
- Warlock
- OutCast
- Rotten
- Wrath Tor RAGE
- Agrostid
- Banana Unsplit
- Gralien
- BalloonsDTM
- Kaldr
- Persisto
- Snowy Wars
- Seahold
- Desolate Gully
- Justice
