name: Default
priority: 1
count: 0
maps:
- Atom
- Snowy Frontier
- Come Summertime
- Garden
- Under The Sea
- Hekla
- Dry Outpost
- Nyah
- Finis
- Mesa
- Downforce
- Wilky Way
- Dead Waters
- Geometric
- Lagoon
- Gelid 2
- The Bug
- Toss Up
- Vertex
- Maple Falls
