name: Default
priority: 1
count: 0
maps:
- "Antiquis: Emerald"
- Novum
- Dawnskirr
- Croak
- Tahiti
- The Fenland CTF
- Boulders
- Immitis FFA
- Hemlock
- Woolirium
- Green
- Cargo
- Fracture DTM
- Deepwind Redux
- Molendinis
- Lost World CTF
- "Coastline: Duo"
- "Buzzard's Trail"
